spring:
  application:
    name: order-service
    
#server:#  port: 8201

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka
      
feign:  httpclient:    enabled: true
    
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
        
---
spring:
  profiles: order1
  rabbitmq:
    host: 192.168.131.131
    port: 5672
    username: admin
    password: admin
  
server:  port: 8201
  
---
spring:
  profiles: order2
  rabbitmq:
    host: 192.168.131.131
    port: 5672
    username: admin
    password: admin
  
server:
  port: 8202